### PR TITLE
Add helpers for String and URI manipulation in templates

### LINKED ISSUE #59: Enable more helpers
I think it could be nice to have more helpers available, for example as those [listed there](https://support.iterable.com/hc/en-us/articles/205480365-Personalizing-Templates-with-Handlebars-). The most useful would be a `replace` helper which changes a string to another. For example, I would like to replace `:` with a dot `.` instead of the default `_`. I guess that other helpers could be useful in other instance.

### LINKED ISSUE #89: Automatically convert colons in title to other symbols, such as "-"
Your plugin offers me a great convience for it  has improved my workflow by strengthening the connection between Obsidian and Zotero. But I just encounted some problem with the placeholder {{title}}.
Since the file name cannot contain some characters shown in this figure, it seems that they cannot appear in aliases as well. **When {{title}} is used in iterature note title template, characters like ":" will be aotumatically converted to "_", which doesn't work if it is used in aliases and results in some mistakes.**
image

### PR DESCRIPTION
**Pull request by byteSamurai**
Because I needed it myself, I added helpers from a helper collection. I consider all helpers a bit overkill, but string and URI helpers should be sufficient for the most use cases.

Closes #59 
Closes #89 too because of `replace` or `dashcase` filter

What happened apart from adding helpers:
- I ran `npm audit fix` since it resolved a couple of issues - not all, but at least.
- `tsconfig.json` was extended with `"esModuleInterop": true,` to use the default exported helper function of the npm package. 
- Within the settings page, links to the helper functions have been added.

@hans Your idea for this plugin is awesome. Would like to help more, if you'd like to.

### CODE REVIEW

**Comment by byteSamurai** [comment]
@hans WDYT?

**Comment by hbhargava7** [comment]
Would love to see helpers added! Is there a list of which helpers are available currently?

**Comment by hans** [comment]
Thanks @byteSamurai for this wonderful contribution! I've just merged into develop and it will be included in the next release.

**Comment by byteSamurai** [comment]
A pleasure, @hans :)

However, I just tried to add author names as normalised tags, which brought me to what you did in the develop branch already. 
I need to admit dependencies of the handlebar helpers are everything but well maintained. I found a way to tweak the rollup config to rewrite the dynamic imports but... it's not beautiful. 

Do you have a specific reason to stick with Handlebars? Maybe [Nunjucks](https://mozilla.github.io/nunjucks/) could be an alternative since it provides a good set of helpers (filters) already.

WDYT?

**Pull request merged**
